data:
  data_location: "./data/nsynth-patch/train/synth_lead_synthetic_000"
  extension: "wav"

preprocess:
  sampling_rate: &samplingrate 48000
  signal_length: &signallength 192000
  block_size: &blocksize 512 # must be a power of 2 if using realtime

  oneshot: false # crop every audio file to exactly signal length
  out_dir: "./cache/nsynth-patch/train/synth_lead_synthetic_000"

model:
  hidden_size: 512
  n_harmonic: 64
  n_bands: 65
  sampling_rate: *samplingrate
  block_size: *blocksize
  has_reverb: True

train:
  scales: [4096,2048, 1024, 512, 256, 128]
  overlap: .75
