data:
  data_location: "./data/rainbow"
  extension: "mp3"

preprocess:
  sample_rate: &samplingrate 48000
  signal_length: &signallength 192000
  block_size: &blocksize 512 # must be a power of 2 if using realtime

  oneshot: false # crop every audio file to exactly signal length
  out_dir: "./cache/string_acoustic_080"

model:
  name: single-inst-decoder
  kwargs:
    hidden_size: 512
    n_harmonic: 64
    n_bands: 65
    sample_rate: *samplingrate
    block_size: *blocksize
    has_reverb: True

train:
  scales: [4096,2048, 1024, 512, 256, 128]
  overlap: .75
  batch: 16
  lr: 1.0e-3
  steps: 500000
